import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{atDistance,lapTime,csv,type Session,type Lap,type Point}from'./telemetry';
import './style.css';
const colors=['#c6f366','#b4a6ff'];
function App(){
 const [data,setData]=useState<Session|null>(null),[error,setError]=useState('');
 const [a,setA]=useState(0),[b,setB]=useState(2),[la,setLa]=useState(0),[lb,setLb]=useState(0),[distance,setDistance]=useState(0),[playing,setPlaying]=useState(false),[rate,setRate]=useState(2),[channel,setChannel]=useState<'speed'|'throttle'|'brake'>('speed');
 useEffect(()=>{fetch('./monza-2024.json').then(r=>{if(!r.ok)throw Error('Unable to load the session.');return r.json()}).then(setData).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!playing||!data)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now(),dt=(now-last)/1000;last=now;setDistance(d=>{const speed=atDistance(data.drivers[a].laps[la].points,d).speed/3.6;const next=d+dt*speed*rate;if(next>=data.distance){setPlaying(false);return data.distance;}return next;});},40);return()=>clearInterval(timer);},[playing,data,a,la,rate]);
 if(!data)return <main><h1>Lap Lab<span>.</span></h1><p role="status">{error||'Loading the Monza session…'}</p>{error&&<button onClick={()=>location.reload()}>Try again</button>}</main>;
 const da=data.drivers[a],db=data.drivers[b],laps=[da.laps[la],db.laps[lb]],pa=atDistance(laps[0].points,distance),pb=atDistance(laps[1].points,distance);
 const gap=laps[1].time-laps[0].time;
 const choose=(side:number,value:number)=>{side===0?(setA(value),setLa(0)):(setB(value),setLb(0));setPlaying(false);};
 const exportCSV=()=>{const url=URL.createObjectURL(new Blob([csv(laps[0])],{type:'text/csv'}));const el=document.createElement('a');el.href=url;el.download=`Monza-2024-${da.code}-lap-${laps[0].number}.csv`;el.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <><header><a className="brand" href="./">LL<span> / </span>LAP LAB</a><span className="header-note">THE DETAILS MAKE THE DIFFERENCE.</span><a href="/projects/f1.html">About this project ↗</a></header><main>
 <section className="intro"><div><p className="eyebrow">FORMULA 1 / TELEMETRY WORKSPACE</p><h1>Find the difference<span>.</span></h1><p>Two drivers. One circuit. Every fraction of a second.</p></div><div className="session"><span className="status-dot"/> HISTORICAL SESSION<strong>Monza <small>2024</small></strong><span>QUALIFYING · 5.793 KM</span></div></section>
 <section className="selector" aria-label="Lap comparison controls">{[da,db].map((d,i)=><div className={'driver driver-'+i} key={i}><span className="slot">0{i+1}</span><label>Driver {i===0?'A · solid':'B · dashed'}<select value={i===0?a:b} onChange={e=>choose(i,+e.target.value)}>{data.drivers.map((d,j)=><option value={j} key={d.number}>{d.name}</option>)}</select></label><label>Qualifying lap<select value={i===0?la:lb} onChange={e=>{i===0?setLa(+e.target.value):setLb(+e.target.value);setPlaying(false);}}>{d.laps.map((l,j)=><option value={j} key={l.number}>Lap {l.number} · {lapTime(l.time)}</option>)}</select></label><span className="team">{d.team}</span></div>)}</section>
 <section className="metrics"><div><span>{da.code} / LAP TIME</span><strong>{lapTime(laps[0].time)}</strong><small>Lap {laps[0].number}</small></div><div><span>{db.code} / LAP TIME</span><strong>{lapTime(laps[1].time)}</strong><small>Lap {laps[1].number}</small></div><div><span>OFFICIAL LAP DIFFERENCE</span><strong className="lime">{Math.abs(gap).toFixed(3)}<em>s</em></strong><small>{gap===0?'Identical lap times':`${gap>0?da.code:db.code} ahead`}</small></div><div><span>TOP SPEED / A vs B</span><strong>{Math.max(...laps[0].points.map(p=>p.speed))}<em> / {Math.max(...laps[1].points.map(p=>p.speed))}</em></strong><small>km/h · sampled telemetry</small></div></section>
 <div className="workspace"><section className="panel trace"><div className="panel-heading"><div><p className="eyebrow">01 / COMPARE</p><h2>The lap, unwrapped.</h2></div><div className="tabs">{(['speed','throttle','brake']as const).map(c=><button aria-pressed={channel===c} onClick={()=>setChannel(c)} key={c}>{c}</button>)}</div></div><div className="legend"><span style={{color:colors[0]}}>━ {da.code} <b>{Math.round(pa[channel])}{channel==='speed'?' km/h':channel==='throttle'?'%':pa.brake?' · on':' · off'}</b></span><span style={{color:colors[1]}}>┄ {db.code} <b>{Math.round(pb[channel])}{channel==='speed'?' km/h':channel==='throttle'?'%':pb.brake?' · on':' · off'}</b></span></div><Chart laps={laps} channel={channel} distance={distance} total={data.distance} onSeek={setDistance}/><div className="playback"><button className="primary" onClick={()=>{if(distance>=data.distance)setDistance(0);setPlaying(!playing);}}>{playing?'Pause':'Play lap'}</button><button aria-label="Restart lap" onClick={()=>{setDistance(0);setPlaying(false);}}>↺</button><label className="scrubber"><span>Lap position <b>{Math.round(distance).toLocaleString()} m</b></span><input aria-label="Lap position" type="range" min="0" max={data.distance} value={distance} onChange={e=>{setDistance(+e.target.value);setPlaying(false);}}/></label><label>Speed<select aria-label="Playback speed" value={rate} onChange={e=>setRate(+e.target.value)}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div></section>
 <section className="panel map"><p className="eyebrow">02 / ON CIRCUIT</p><h2>Temple of speed.</h2><Track lap={laps[0]} points={[pa,pb]}/><div className="readout"><div><span>{da.code} GEAR</span><strong>{pa.gear}</strong></div><div><span>{da.code} RPM</span><strong>{Math.round(pa.rpm).toLocaleString()}</strong></div><div><span>BRAKE</span><strong className={pa.brake?'lime':''}>{pa.brake?'ON':'OFF'}</strong></div></div></section></div>
 <section className="panel sectors"><div><p className="eyebrow">03 / WHERE IT HAPPENS</p><h2>Three sectors. The full story.</h2><p>Official sector timing, independent of the sampled traces.</p></div><div className="sector-grid">{[0,1,2].map(i=>{const diff=laps[1].sectors[i]-laps[0].sectors[i];return <div key={i}><span>SECTOR 0{i+1}</span><strong>{Math.abs(diff).toFixed(3)}<small>s</small></strong><p>{diff===0?'Even':`${diff>0?da.code:db.code} faster`}</p><div className="sector-times"><span>{da.code} {laps[0].sectors[i].toFixed(3)}</span><span>{db.code} {laps[1].sectors[i].toFixed(3)}</span></div></div>;})}</div></section>
 <footer><p><strong>Real laps. Reproducible analysis.</strong><br/>OpenF1 historical data · Four drivers, two fastest recorded laps each.<br/>Distance is estimated by integrating speed and normalized to circuit length. Position is sampled; overlays are approximate. Recorded laps may include deleted times.</p><div><button onClick={exportCSV}>Export driver A CSV ↓</button><a href="https://openf1.org/" target="_blank" rel="noreferrer">Data source ↗</a></div></footer>
 </main></>;
}
function Chart({laps,channel,distance,total,onSeek}:{laps:Lap[];channel:'speed'|'throttle'|'brake';distance:number;total:number;onSeek:(d:number)=>void}){
 const max=channel==='speed'?360:channel==='throttle'?100:1;const x=(d:number)=>48+d/total*840,y=(v:number)=>218-v/max*180;
 return <svg className="chart" viewBox="0 0 910 255" role="img" aria-label={`${channel} by estimated lap distance. Use the lap position slider to inspect values.`} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek(Math.max(0,Math.min(total,((e.clientX-r.left)/r.width*910-48)/840*total)));}}>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1="48" x2="888" y1={y(f*max)} y2={y(f*max)} stroke="#30393b"/><text x="36" y={y(f*max)+4} textAnchor="end">{Math.round(f*max*100)/100}</text></g>)}{[0,1000,2000,3000,4000,5000].map(d=><text key={d} x={x(d)} y="245" textAnchor="middle">{d} m</text>)}{laps.map((l,i)=><polyline key={i} fill="none" stroke={colors[i]} strokeWidth="2.4" strokeDasharray={i===1?'7 4':undefined} points={l.points.map(p=>`${x(p.d)},${y(p[channel])}`).join(' ')}/>)}<line x1={x(distance)} x2={x(distance)} y1="25" y2="223" stroke="#fff" strokeDasharray="3 4"/>{laps.map((l,i)=><circle key={i} cx={x(distance)} cy={y(atDistance(l.points,distance)[channel])} r="5" fill={colors[i]} stroke="#151c1e" strokeWidth="2"/>)}</svg>;
}
function Track({lap,points}:{lap:Lap;points:Point[]}){const xs=lap.points.map(p=>p.x),ys=lap.points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const scale=Math.min(310/(maxX-minX),195/(maxY-minY));const x=(n:number)=>25+(n-minX)*scale+(310-(maxX-minX)*scale)/2,y=(n:number)=>220-(n-minY)*scale;return <svg viewBox="0 0 360 250" role="img" aria-label="Monza circuit with current position of both drivers"><polyline fill="none" stroke="#3d4948" strokeWidth="9" strokeLinejoin="round" points={lap.points.map(p=>`${x(p.x)},${y(p.y)}`).join(' ')}/><polyline fill="none" stroke="#71817b" strokeWidth="1" points={lap.points.map(p=>`${x(p.x)},${y(p.y)}`).join(' ')}/>{points.map((p,i)=><g key={i}><circle cx={x(p.x)} cy={y(p.y)} r={i===0?7:5} fill={colors[i]} stroke="#151c1e" strokeWidth="2"/><text x={x(p.x)+10} y={y(p.y)+(i===0?-10:17)} fill={colors[i]}>{i===0?'A':'B'}</text></g>)}</svg>;}
createRoot(document.getElementById('root')!).render(<App/>);
